version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'
  protoc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    labels:
      - "protobuf_converter"
volumes:
  rabbitmq_data:
